#!/usr/bin/env python3
"""
src/mutagenesis/03a_prep_dca_jobs.py

Prepare per-gene plmDCA job directories for HPC and write the SLURM array script.

Run locally before transferring to HPC:
  conda run -n oxphos_dav python src/mutagenesis/03a_prep_dca_jobs.py

Outputs:
  data/dca_jobs/{gene}/aln.fasta     — full alignment (sanitized, no subsampling)
  data/dca_jobs/gene_list.tsv        — gene, genome, n_seqs, aln_len
  scripts/slurm_dca_array.sh         — SLURM array script (auto-generated)
"""

import sys
from pathlib import Path

from Bio import SeqIO

ROOT         = Path(__file__).resolve().parents[2]
CONTACTS_CSV = ROOT / "results" / "structural" / "dar_contacts_cbcb8A.csv"
ALN_NUC      = ROOT / "data" / "alignments" / "toga_hg38_aa"
ALN_MT       = ROOT / "data" / "alignments" / "mtdna_aa"
JOBS_DIR     = ROOT / "data" / "dca_jobs"
SLURM_OUT    = ROOT / "scripts" / "slurm_dca_array.sh"
HPC_HOME     = "/home/ad2347/OxPhos_DAV"          # code: src/, scripts/, setup.py
HPC_WORK     = "/work/WorkDevelopmentC/ad2347/OxPhos_DAV"  # data: data/, results/, logs/

_ALIAS = {"COXFA4": "NDUFA4", "NDUFA4": "COXFA4"}
_MASK_TO_GAP = str.maketrans("*!X", "---")


def _find_aln(gene: str) -> tuple[Path | None, str]:
    for aln_dir, genome in ((ALN_MT, "mtDNA"), (ALN_NUC, "nucDNA")):
        for name in (gene, _ALIAS.get(gene, "")):
            if not name:
                continue
            p = aln_dir / f"{name}_aa_alignment.fasta"
            if p.exists():
                return p, genome
    return None, ""


def main():
    try:
        import pandas as pd
    except ImportError:
        sys.exit("pandas required: conda activate oxphos_dav")

    if not CONTACTS_CSV.exists():
        sys.exit(f"ERROR: {CONTACTS_CSV} not found — run structural stage first.")

    contacts = pd.read_csv(CONTACTS_CSV, low_memory=False)
    gene_col  = "dar_locus" if "dar_locus" in contacts.columns else "dar_gene"
    dar_genes = sorted(contacts[gene_col].dropna().unique())
    print(f"Unique DAR genes in contacts CSV: {len(dar_genes)}")

    JOBS_DIR.mkdir(parents=True, exist_ok=True)

    gene_list_rows = []
    job_dirs = []

    for gene in dar_genes:
        aln_path, genome = _find_aln(gene)
        if aln_path is None:
            print(f"  [SKIP] {gene}: no alignment found")
            continue

        recs = list(SeqIO.parse(str(aln_path), "fasta"))
        if len(recs) < 10:
            print(f"  [SKIP] {gene}: only {len(recs)} sequences")
            continue

        L = len(str(recs[0].seq))

        # Write sanitized alignment (stop codons → gaps)
        job_dir = JOBS_DIR / gene
        job_dir.mkdir(exist_ok=True)
        out_fasta = job_dir / "aln.fasta"
        with open(out_fasta, "w") as f:
            for rec in recs:
                seq = str(rec.seq).upper().translate(_MASK_TO_GAP)
                f.write(f">{rec.id}\n{seq}\n")

        n_seqs = len(recs)
        gene_list_rows.append(f"{gene}\t{genome}\t{n_seqs}\t{L}")
        job_dirs.append(gene)
        print(f"  [OK]   {gene} ({genome}): {n_seqs} seqs × {L} cols")

    # Write gene list
    gene_list_path = JOBS_DIR / "gene_list.tsv"
    with open(gene_list_path, "w") as f:
        f.write("gene\tgenome\tn_seqs\taln_len\n")
        for row in gene_list_rows:
            f.write(row + "\n")
    print(f"\nGene list → {gene_list_path}  ({len(job_dirs)} genes)")

    # Write SLURM array script
    n = len(job_dirs)
    gene_array = " ".join(job_dirs)
    script = f"""\
#!/bin/bash
#SBATCH --job-name=dca_all_davs
#SBATCH --array=1-{n}
#SBATCH --cpus-per-task=8
#SBATCH --mem=64G
#SBATCH --time=6:00:00
#SBATCH --output={HPC_WORK}/logs/dca_%A_%a.out
#SBATCH --error={HPC_WORK}/logs/dca_%A_%a.err
#
# Auto-generated by src/mutagenesis/03a_prep_dca_jobs.py — do not edit manually.
#
# ── TRANSFER (run locally) ───────────────────────────────────────────────────
#   rsync -av data/dca_jobs/ hpc:{HPC_WORK}/data/dca_jobs/
#   rsync -av results/structural/dar_contacts_cbcb8A.csv \\
#       hpc:{HPC_WORK}/results/structural/
#   rsync -av src/ hpc:{HPC_HOME}/src/
#   rsync -av setup.py hpc:{HPC_HOME}/
#   rsync -av scripts/slurm_dca_array.sh hpc:{HPC_HOME}/scripts/
#
# ── SUBMIT ───────────────────────────────────────────────────────────────────
#   mkdir -p {HPC_WORK}/logs {HPC_WORK}/results/mutagenesis/dca_gene_results
#   sbatch {HPC_HOME}/scripts/slurm_dca_array.sh
#
# ── COPY RESULTS BACK ────────────────────────────────────────────────────────
#   rsync -av hpc:{HPC_WORK}/results/mutagenesis/dca_gene_results/ \\
#       results/mutagenesis/dca_gene_results/
#
# ── AGGREGATE LOCALLY ────────────────────────────────────────────────────────
#   docker run --rm -v $(pwd):/app oxphos_dav_analysis conda run -n oxphos_dav \\
#       python src/mutagenesis/03_dca_all_davs.py \\
#       --aggregate results/mutagenesis/dca_gene_results/
# ─────────────────────────────────────────────────────────────────────────────

set -euo pipefail

HPC_HOME="{HPC_HOME}"
HPC_WORK="{HPC_WORK}"
GENES=({gene_array})
GENE="${{GENES[${{SLURM_ARRAY_TASK_ID}}-1]}}"

module load miniconda/2024-02-20
eval "$(conda shell.bash hook)"
conda activate OXPHOS_DAV

export OMP_NUM_THREADS=${{SLURM_CPUS_PER_TASK:-8}}
export OPENBLAS_NUM_THREADS=${{SLURM_CPUS_PER_TASK:-8}}
export MKL_NUM_THREADS=${{SLURM_CPUS_PER_TASK:-8}}

mkdir -p "$HPC_WORK/logs" "$HPC_WORK/results/mutagenesis/dca_gene_results"

echo "Gene: $GENE  Host: $(hostname)  Date: $(date)"
echo "CPUs: ${{SLURM_CPUS_PER_TASK:-8}}  Mem: $(free -h | awk '/^Mem/{{print $2}}')"

python "$HPC_HOME/src/mutagenesis/03b_dca_gene_worker.py" \\
    "$GENE" \\
    "$HPC_WORK/data/dca_jobs/$GENE/aln.fasta" \\
    "$HPC_WORK/results/mutagenesis/dca_gene_results/${{GENE}}.npz"

echo "Done: $GENE  $(date)"
"""
    SLURM_OUT.parent.mkdir(exist_ok=True)
    SLURM_OUT.write_text(script)
    SLURM_OUT.chmod(0o755)
    print(f"SLURM script ({n} jobs) → {SLURM_OUT}")

    print(f"""
Next steps:
  1. rsync -av data/dca_jobs/ hpc:{HPC_WORK}/data/dca_jobs/
  2. rsync -av results/structural/dar_contacts_cbcb8A.csv \\
         hpc:{HPC_WORK}/results/structural/
  3. rsync -av src/ hpc:{HPC_HOME}/src/
  4. rsync -av setup.py hpc:{HPC_HOME}/
  5. rsync -av scripts/slurm_dca_array.sh hpc:{HPC_HOME}/scripts/
  6. On HPC: mkdir -p {HPC_WORK}/logs {HPC_WORK}/results/mutagenesis/dca_gene_results
  7. On HPC: sbatch {HPC_HOME}/scripts/slurm_dca_array.sh
  8. rsync -av hpc:{HPC_WORK}/results/mutagenesis/dca_gene_results/ \\
         results/mutagenesis/dca_gene_results/
  9. Aggregate locally (see script header)
""")


if __name__ == "__main__":
    main()
