---
title: "OxPhos Disease-Associated Variant Analysis"
author: "Abhilesh Dhawanjewar"
format:
    html:
        code-fold: true
        embed-resources: true
        toc: true
        toc-location: left
        html-math-method: katex
        theme: cosmo
execute:
    echo: false
    warning: false
    message: false
---

```{r}
#| label: setup

library(here)
```

## Data Sources

#### Cannonical OXPHOS Gene List

The list of canonical OXPHOS genes was obtained from the HUGO Gene Nomenclature Committee database for gene group: [Mitochondrial respiratory chain complex subunits](https://www.genenames.org/data/genegroup/#!/group/639)

#### Disease Variant Annotations

Missense disease-associated variants for mtDNA were retrieved from the [MITOMAP database](https://www.mitomap.org/MITOMAP/MutationsCodingControl) for mitochondrial genes and from the [ClinVar database](https://ftp.ncbi.nlm.nih.gov/pub/clinvar/tab_delimited/variant_summary.txt.gz) for nuclear-encoded OXPHOS genes.

The reference genome for these annotations were:

- mtDNA: `NC_012920.1` (rCRS) for mtDNA
- nucDNA: `GRCh38` for nuclear DNA.

#### Supplementary Variant Data

The following databases were used to supplement the disease variant annotations with additional information such as computational pathogenecity predictions, haplogroup associations and population allele frequencies.

mtDNA variant information

- [MitImpact3D](https://mitimpact.mcb2lab.org/) (`v3.1.3`): Computational pathogenicity predictions for missense variants in mitochondrial genes
- [PhyloTree](https://www.phylotree.org/rCRS-oriented_version.htm) (`Build 17`): mtDNA haplogroup associations for variants

nucDNA variant information

- [gnomAD](https://gnomad.broadinstitute.org/) (`v4.1`): Population allele frequencies and gene-level constraint metrics (pLI, LOEUF, missense oe, missense z-score) for nuclear genes
- [dbNSFP](https://www.dbnsfp.org/) ()
