"""
src/phylo/prepare_pagel_hpc.py

Prepares Pagel's discrete test inputs for parallel execution on HPC.

Runs Pass 1 of the compensatory partners analysis (Fisher + branch co-occurrence)
and writes all Pagel input files (pruned trees, binary trait files) to a permanent
directory, then splits the manifest into SLURM array chunks.

Inputs (must already exist):
  results/structural/all_tested_pairs.csv                        -- from 01_find_compensating_partners.py
  data/phylo/ancestral_state_maps.json                           -- from 01_parse_ancestral_states.py
  data/phylo/species_tree/mammaltree_crossgenome.nwk
  data/derived/classified/variants_master_classified.parquet
  data/alignments/toga_hg38_aa/  and  data/alignments/mtdna_aa/

Outputs:
  data/phylo/pagel_jobs/
    manifest.tsv                  -- all Pagel-eligible pairs
    all_records_index.json        -- rec_idx → identity key for merge
    trees/tree_NNNN.nwk           -- unique pruned topologies (relative paths)
    traits/t1_NNNN.txt            -- binary trait files (relative paths)
    traits/t2_NNNN.txt
    chunks/chunk_NNNN.tsv         -- manifest split into HPC chunks
  scripts/slurm_pagel_array.sh    -- SLURM job array script

Run from project root inside the Docker container:
    python src/phylo/prepare_pagel_hpc.py

Transfer to HPC:
    rsync -av data/phylo/pagel_jobs/ lambda:/work/WorkDevelopmentC/ad2347/OxPhos_DAV/data/phylo/pagel_jobs/
    rsync -av src/ scripts/slurm_pagel_array.sh lambda:/home/ad2347/OxPhos_DAV/
"""

import copy
import csv
import json
import sys
from collections import defaultdict
from pathlib import Path

import pandas as pd
from Bio import Phylo
from scipy.stats import fisher_exact

# ── Paths ──────────────────────────────────────────────────────────────────────
ROOT               = Path(__file__).resolve().parents[2]
DATA_DIR           = ROOT / "data"
CLASSIFIED_PARQUET = ROOT / "data" / "derived" / "classified" / "variants_master_classified.parquet"
CONTACTS           = ROOT / "results" / "structural" / "dar_contacts_cbcb8A.csv"
ANC_MAPS    = DATA_DIR / "phylo" / "ancestral_state_maps.json"
VERT_TREE   = DATA_DIR / "phylo" / "species_tree" / "mammaltree_crossgenome.nwk"
CROSS_SPP   = DATA_DIR / "phylo" / "cross_genome_species.txt"

JOBS_DIR    = DATA_DIR / "phylo" / "pagel_jobs"
SCRIPTS_DIR = ROOT / "scripts"

PAGEL_R     = ROOT / "src" / "phylo" / "pagel_discrete.R"

_MASK           = {"-", "X", "!", "*"}
_PAGEL_MIN_SPP  = 20
_FISHER_PREFILTER = 0.20   # only run Pagel where Fisher p < this
_CHUNK_SIZE     = 100      # pairs per SLURM task
HPC_HOME        = "/home/ad2347/OxPhos_DAV"
HPC_WORK        = "/work/WorkDevelopmentC/ad2347/OxPhos_DAV"


# ── Import partners helpers (handle module name with hyphen) ──────────────────

def _import_partners():
    """Import helpers from 01_find_compensating_partners.py."""
    import importlib.util
    partners_path = ROOT / "src" / "structural" / "01_find_compensating_partners.py"
    spec = importlib.util.spec_from_file_location("partners", partners_path)
    mod  = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


# ── SLURM script writer ───────────────────────────────────────────────────────

def write_slurm_script(n_chunks: int, out_path: Path):
    script = f"""\
#!/bin/bash
#SBATCH --job-name=pagel_oxphos
#SBATCH --array=1-{n_chunks}
#SBATCH --cpus-per-task=1
#SBATCH --mem=4G
#SBATCH --time=6:00:00
#SBATCH --output={HPC_WORK}/logs/pagel_%A_%a.out
#SBATCH --error={HPC_WORK}/logs/pagel_%A_%a.err

# Auto-generated by src/phylo/prepare_pagel_hpc.py — do not edit manually.
#
# Transfer inputs (run locally first):
#   rsync -av data/phylo/pagel_jobs/ hpc:{HPC_WORK}/data/phylo/pagel_jobs/
#   rsync -av src/ hpc:{HPC_HOME}/src/
#   rsync -av scripts/slurm_pagel_array.sh hpc:{HPC_HOME}/scripts/
#
# Submit on HPC:
#   mkdir -p {HPC_WORK}/results/phylo/pagel_results {HPC_WORK}/logs
#   sbatch {HPC_HOME}/scripts/slurm_pagel_array.sh
#
# Copy results back:
#   rsync -av hpc:{HPC_WORK}/results/phylo/pagel_results/ data/phylo/pagel_results/
#
# Merge locally:
#   docker run --rm -v $(pwd):/app oxphos_dav_analysis conda run -n oxphos_dav \\
#       python src/phylo/merge_pagel_results.py

set -euo pipefail

module load miniconda/2024-02-20
eval "$(conda shell.bash hook)"
conda activate OXPHOS_DAV

CHUNK=$(printf "%04d" ${{SLURM_ARRAY_TASK_ID}})
HPC_HOME="{HPC_HOME}"
HPC_WORK="{HPC_WORK}"
PAGEL_JOBS="$HPC_WORK/data/phylo/pagel_jobs"
OUT_DIR="$HPC_WORK/results/phylo/pagel_results"
mkdir -p "$OUT_DIR" "$HPC_WORK/logs"

# Paths inside chunk TSV are relative to pagel_jobs/ — cd there first
cd "$PAGEL_JOBS"

Rscript "$HPC_HOME/src/phylo/pagel_discrete.R" \\
    "chunks/chunk_${{CHUNK}}.tsv" \\
    "$OUT_DIR/results_${{CHUNK}}.tsv"

echo "Done: chunk $CHUNK"
"""
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(script)
    out_path.chmod(0o755)
    print(f"SLURM script ({n_chunks} tasks) → {out_path}")


# ── Main ───────────────────────────────────────────────────────────────────────

def main():
    # ── Import helpers from partners script ───────────────────────────────────
    print("Loading helpers from 01_find_compensating_partners.py ...")
    p = _import_partners()
    load_alignments      = p.load_alignments
    build_pos_to_col     = p.build_pos_to_col
    get_ref_seq          = p.get_ref_seq
    load_cross_genome_species = p.load_cross_genome_species

    # ── Prerequisite check ────────────────────────────────────────────────────
    for f in (CLASSIFIED_PARQUET, CONTACTS, VERT_TREE):
        if not f.exists():
            print(f"ERROR: {f} not found.")
            sys.exit(1)

    # ── Load data (same as partners script Pass 1) ────────────────────────────
    cdavs: dict = {}
    df = pd.read_parquet(CLASSIFIED_PARQUET)
    for var in df[
        (df["classification_status"] == "classified") &
        (df["is_cdav_amino_acid"] == True)
    ].to_dict(orient="records"):
        if "Discarded" in str(var.get("tier", "")):
            continue
        cdavs[var["ann_id"]] = var
    print(f"Non-discarded cDAVs: {len(cdavs)}")

    contacts: list[dict] = []
    with open(CONTACTS) as f:
        for row in csv.DictReader(f):
            if row["ann_id"] in cdavs:
                contacts.append(row)
    print(f"Contacts for these DARs: {len(contacts)}")

    needed_genes = {
        g for row in contacts
        for g in (row["dar_locus"], row["contact_gene"])
        if not g.startswith("Unknown(")
    }
    alns = p.load_alignments(needed_genes)
    print(f"Alignments loaded for {len(alns)} genes.")

    anc_maps: dict = {}
    if ANC_MAPS.exists():
        with open(ANC_MAPS) as f:
            anc_maps = json.load(f)
        print(f"Ancestral state maps: {len(anc_maps)} genes.")

    cross_genome_spp = load_cross_genome_species()
    print(f"Cross-genome species: {len(cross_genome_spp)}")

    print(f"Loading MamPhy tree ...")
    master_tree = Phylo.read(str(VERT_TREE), "newick")
    all_tips = {c.name for c in master_tree.get_terminals()}
    print(f"  {len(all_tips)} tips.\n")

    # ── Pass 1: build all_records + pagel_pending ─────────────────────────────
    by_dar: dict = defaultdict(list)
    for row in contacts:
        by_dar[row["ann_id"]].append(row)

    all_records:    list[dict]  = []
    pagel_pending:  list[tuple] = []   # (rec_idx, dar_spp, test_spp, contact_alt_spp, key_str)

    for ann_id, dar_contacts in by_dar.items():
        var          = cdavs[ann_id]
        dar_gene     = (
            var.get("interpreted_gene")
            or var.get("classification_gene")
            or str(var.get("locus", "")).split("/")[0]
        )
        cdav_spp     = set(var.get("lineages_with_disease_allele", []))
        dar_aa_coord = int(dar_contacts[0]["dar_aa_coord"])

        if dar_gene not in alns:
            continue
        dar_aln = alns[dar_gene]
        try:
            _, dar_ref_gapped = get_ref_seq(dar_aln)
        except ValueError:
            continue
        dar_col_map = build_pos_to_col(dar_ref_gapped)
        if dar_aa_coord not in dar_col_map:
            continue
        dar_col = dar_col_map[dar_aa_coord]

        readable_spp = {
            sp for sp, seq in dar_aln.items()
            if sp != "Homo_sapiens" and len(seq) > dar_col
            and seq[dar_col] not in _MASK
        }
        cdav_in_aln = cdav_spp & readable_spp
        bg_spp      = readable_spp - cdav_spp
        if not cdav_in_aln:
            continue

        seen_contacts: set = set()

        for row in dar_contacts:
            contact_gene = row["contact_gene"]
            if contact_gene.startswith("Unknown(") or contact_gene not in alns:
                continue
            try:
                contact_pos = int(row["contact_refseq_pos"])
            except (ValueError, TypeError):
                continue
            key_c = (contact_gene, contact_pos)
            if key_c in seen_contacts:
                continue
            seen_contacts.add(key_c)

            c_aln = alns[contact_gene]
            try:
                _, c_ref_gapped = get_ref_seq(c_aln)
            except ValueError:
                continue
            c_col_map = build_pos_to_col(c_ref_gapped)
            if contact_pos not in c_col_map:
                continue
            c_col = c_col_map[contact_pos]

            human_contact_aa = row["contact_aa"]
            contact_type     = row["contact_type"]

            cdav_contact_aas = [
                c_aln[sp][c_col]
                for sp in cdav_in_aln
                if sp in c_aln and len(c_aln[sp]) > c_col
                and c_aln[sp][c_col] not in _MASK
            ]
            bg_contact_aas = [
                c_aln[sp][c_col]
                for sp in bg_spp
                if sp in c_aln and len(c_aln[sp]) > c_col
                and c_aln[sp][c_col] not in _MASK
            ]

            if not cdav_contact_aas:
                continue

            for alt_aa in {aa for aa in cdav_contact_aas if aa != human_contact_aa}:
                a = cdav_contact_aas.count(alt_aa)
                if a == 0:
                    continue
                c = len(cdav_contact_aas) - a
                b = bg_contact_aas.count(alt_aa)

                _, fisher_p = fisher_exact([[a, b], [c, len(bg_contact_aas) - b]],
                                            alternative="greater")

                contact_alt_spp = {
                    sp for sp in readable_spp
                    if sp in c_aln and len(c_aln[sp]) > c_col
                    and c_aln[sp][c_col] == alt_aa
                }
                test_spp = readable_spp
                if contact_type == "mt-nuc" and cross_genome_spp:
                    test_spp = test_spp & cross_genome_spp
                n_test   = len(test_spp)
                low_power = n_test < _PAGEL_MIN_SPP

                rec_idx = len(all_records)
                identity_key = f"{ann_id}|{contact_gene}|{contact_pos}|{alt_aa}"

                all_records.append({
                    "ann_id":           ann_id,
                    "contact_gene":     contact_gene,
                    "contact_pos":      contact_pos,
                    "contact_alt_aa":   alt_aa,
                    "identity_key":     identity_key,
                    "fisher_p":         fisher_p,
                    "low_power":        low_power,
                    "n_species_in_test": n_test,
                })

                if not low_power and fisher_p < _FISHER_PREFILTER:
                    pagel_pending.append(
                        (rec_idx, cdav_in_aln, test_spp, contact_alt_spp, identity_key)
                    )

    print(f"\nTotal pairs: {len(all_records)}")
    print(f"Pagel-eligible (Fisher p < {_FISHER_PREFILTER}, N >= {_PAGEL_MIN_SPP}): "
          f"{len(pagel_pending)}")

    # ── Write index JSON (rec_idx → identity key) ─────────────────────────────
    JOBS_DIR.mkdir(parents=True, exist_ok=True)
    index = {str(r["identity_key"]): int(i)
             for i, r in enumerate(all_records)}
    with open(JOBS_DIR / "all_records_index.json", "w") as f:
        json.dump(index, f)
    print(f"Index → {JOBS_DIR / 'all_records_index.json'}")

    # ── Build pruned tree files + trait files ─────────────────────────────────
    trees_dir  = JOBS_DIR / "trees"
    traits_dir = JOBS_DIR / "traits"
    trees_dir.mkdir(exist_ok=True)
    traits_dir.mkdir(exist_ok=True)

    _tree_cache: dict[frozenset, str] = {}   # frozenset(test_spp) → relative tree path
    manifest_lines: list[str] = []

    print(f"\nBuilding tree + trait files for {len(pagel_pending)} pairs ...")

    for idx, (rec_idx, dar_spp, test_spp, contact_alt_spp, identity_key) in enumerate(pagel_pending):
        test_frozen = frozenset(test_spp)

        # Pruned tree — cache by species set
        if test_frozen not in _tree_cache:
            keep = test_frozen & all_tips
            if len(keep) < _PAGEL_MIN_SPP:
                _tree_cache[test_frozen] = None
                continue
            t = copy.deepcopy(master_tree)
            remove = {c.name for c in t.get_terminals()} - keep
            for name in remove:
                t.prune(name)
            pruned_spp = frozenset(c.name for c in t.get_terminals())
            if len(pruned_spp) < _PAGEL_MIN_SPP:
                _tree_cache[test_frozen] = None
                continue
            tree_rel = f"trees/tree_{len(_tree_cache):04d}.nwk"
            Phylo.write(t, str(JOBS_DIR / tree_rel), "newick")
            _tree_cache[test_frozen] = (tree_rel, pruned_spp)
        else:
            if _tree_cache[test_frozen] is None:
                continue

        tree_rel, pruned_spp = _tree_cache[test_frozen]

        t1_rel = f"traits/t1_{idx:04d}.txt"
        t2_rel = f"traits/t2_{idx:04d}.txt"

        with open(JOBS_DIR / t1_rel, "w") as f:
            for sp in pruned_spp:
                f.write(f"{sp}\t{1 if sp in dar_spp else 0}\n")
        with open(JOBS_DIR / t2_rel, "w") as f:
            for sp in pruned_spp:
                f.write(f"{sp}\t{1 if sp in contact_alt_spp else 0}\n")

        manifest_lines.append(f"{identity_key}\t{tree_rel}\t{t1_rel}\t{t2_rel}")

        if (idx + 1) % 500 == 0:
            print(f"  {idx+1}/{len(pagel_pending)} pairs prepared  "
                  f"({len(_tree_cache)} unique topologies so far)")

    n_unique_trees = sum(1 for v in _tree_cache.values() if v is not None)
    print(f"\nTotal pairs in manifest: {len(manifest_lines)}")
    print(f"Unique pruned tree topologies: {n_unique_trees}")

    # ── Write full manifest ───────────────────────────────────────────────────
    manifest_path = JOBS_DIR / "manifest.tsv"
    with open(manifest_path, "w") as f:
        f.write("\n".join(manifest_lines) + "\n")
    print(f"Manifest → {manifest_path}")

    # ── Split into chunks ─────────────────────────────────────────────────────
    chunks_dir = JOBS_DIR / "chunks"
    chunks_dir.mkdir(exist_ok=True)
    chunk_paths: list[Path] = []

    for i in range(0, len(manifest_lines), _CHUNK_SIZE):
        chunk_lines = manifest_lines[i : i + _CHUNK_SIZE]
        chunk_idx   = i // _CHUNK_SIZE + 1
        chunk_path  = chunks_dir / f"chunk_{chunk_idx:04d}.tsv"
        with open(chunk_path, "w") as f:
            f.write("\n".join(chunk_lines) + "\n")
        chunk_paths.append(chunk_path)

    n_chunks = len(chunk_paths)
    print(f"Chunks ({_CHUNK_SIZE} pairs each): {n_chunks}  → {chunks_dir}")

    # ── Write SLURM script ────────────────────────────────────────────────────
    slurm_path = SCRIPTS_DIR / "slurm_pagel_array.sh"
    write_slurm_script(n_chunks, slurm_path)

    # ── Instructions ──────────────────────────────────────────────────────────
    print(f"""
{'='*60}
Next steps:
  1. Transfer to HPC:
       rsync -av data/phylo/pagel_jobs/ hpc:{HPC_WORK}/data/phylo/pagel_jobs/
       rsync -av src/ hpc:{HPC_HOME}/src/
       rsync -av scripts/slurm_pagel_array.sh hpc:{HPC_HOME}/scripts/

  2. On HPC:
       mkdir -p {HPC_WORK}/results/phylo/pagel_results {HPC_WORK}/logs
       sbatch {HPC_HOME}/scripts/slurm_pagel_array.sh

  3. After completion, transfer results back:
       rsync -av hpc:{HPC_WORK}/results/phylo/pagel_results/ data/phylo/pagel_results/

  4. Merge results locally:
       docker run --rm -v $(pwd):/app oxphos_dav_analysis conda run -n oxphos_dav \\
           python src/phylo/merge_pagel_results.py
{'='*60}
""")


if __name__ == "__main__":
    main()
