#!/bin/bash
#SBATCH --job-name=iqtree_oxphos
#SBATCH --array=1-96
#SBATCH --cpus-per-task=4
#SBATCH --mem=8G
#SBATCH --time=4:00:00
#SBATCH --output=/work/WorkDevelopmentC/ad2347/OxPhos_DAV/logs/iqtree_%A_%a.out
#SBATCH --error=/work/WorkDevelopmentC/ad2347/OxPhos_DAV/logs/iqtree_%A_%a.err
#SBATCH --export=ALL
#SBATCH --mail-type=FAIL,BEGIN,END
#SBATCH --mail-user=abhilesh7@gmail.com

# Auto-generated by src/phylo/00_prep_iqtree_jobs.py — do not edit manually.
#
# Transfer inputs:
#   rsync -av data/phylo/iqtree_jobs/ hpc:/work/WorkDevelopmentC/ad2347/OxPhos_DAV/data/phylo/iqtree_jobs/
#   rsync -av scripts/slurm_iqtree_array.sh hpc:/home/ad2347/OxPhos_DAV/scripts/
# Submit:
#   mkdir -p /work/WorkDevelopmentC/ad2347/OxPhos_DAV/logs
#   sbatch /home/ad2347/OxPhos_DAV/scripts/slurm_iqtree_array.sh
# Copy results back:
#   rsync -av hpc:/work/WorkDevelopmentC/ad2347/OxPhos_DAV/data/phylo/ancestral_states/ \
#       data/phylo/ancestral_states/

set -euo pipefail

# Activate IQTree via conda (adjust env name as needed on your HPC)
module load miniconda/2024-02-20
eval "$(conda shell.bash hook)"
conda activate OXPHOS_DAV

GENES=(ATP5F1A ATP5F1B ATP5F1C ATP5F1D ATP5F1E ATP5IF1 ATP5MC1 ATP5MC2 ATP5MC3 ATP5ME ATP5MF ATP5MG ATP5MJ ATP5MK ATP5PB ATP5PD ATP5PF ATP5PO COX4I1 COX4I2 COX5A COX5B COX6A1 COX6A2 COX6B1 COX6B2 COX6C COX7A1 COX7A2 COX7B COX7B2 COX7C COX8A COX8C COXFA4 COXFA4L2 COXFA4L3 CYC1 MT-ATP6 MT-ATP8 MT-ND1 MT-ND2 MT-ND3 MT-ND4 MT-ND4L MT-ND5 MT-ND6 NDUFA1 NDUFA10 NDUFA11 NDUFA12 NDUFA13 NDUFA2 NDUFA3 NDUFA5 NDUFA6 NDUFA7 NDUFA8 NDUFA9 NDUFAB1 NDUFB1 NDUFB10 NDUFB11 NDUFB2 NDUFB3 NDUFB4 NDUFB5 NDUFB6 NDUFB7 NDUFB8 NDUFB9 NDUFC1 NDUFC2 NDUFS1 NDUFS2 NDUFS3 NDUFS4 NDUFS5 NDUFS6 NDUFS7 NDUFS8 NDUFV1 NDUFV2 NDUFV3 SDHA SDHB SDHC SDHD UQCR10 UQCR11 UQCRB UQCRC1 UQCRC2 UQCRFS1 UQCRH UQCRQ)
GENE="${GENES[${SLURM_ARRAY_TASK_ID}-1]}"

HPC_WORK="/work/WorkDevelopmentC/ad2347/OxPhos_DAV"
JOB_DIR="${HPC_WORK}/data/phylo/iqtree_jobs/$GENE"
OUT_DIR="${HPC_WORK}/data/phylo/ancestral_states/$GENE"
mkdir -p "$OUT_DIR" "${HPC_WORK}/logs"

cd "$JOB_DIR" || { echo "Cannot cd to $JOB_DIR"; exit 1; }

iqtree \
    -s "${GENE}.fasta" \
    -te "${GENE}_tree.nwk" \
    -m TEST \
    --ancestral \
    --prefix "$OUT_DIR/$GENE" \
    -T 4 \
    --quiet

echo "Done: $GENE"
