#!/bin/bash
#SBATCH --job-name=dca_all_davs
#SBATCH --array=1-87
#SBATCH --cpus-per-task=8
#SBATCH --mem=64G
#SBATCH --time=6:00:00
#SBATCH --output=/work/WorkDevelopmentC/ad2347/OxPhos_DAV/logs/dca_%A_%a.out
#SBATCH --error=/work/WorkDevelopmentC/ad2347/OxPhos_DAV/logs/dca_%A_%a.err
#
# Auto-generated by src/mutagenesis/03a_prep_dca_jobs.py — do not edit manually.
#
# ── TRANSFER (run locally) ───────────────────────────────────────────────────
#   rsync -av data/dca_jobs/ hpc:/work/WorkDevelopmentC/ad2347/OxPhos_DAV/data/dca_jobs/
#   rsync -av results/structural/dar_contacts_cbcb8A.csv \
#       hpc:/work/WorkDevelopmentC/ad2347/OxPhos_DAV/results/structural/
#   rsync -av src/ hpc:/home/ad2347/OxPhos_DAV/src/
#   rsync -av setup.py hpc:/home/ad2347/OxPhos_DAV/
#   rsync -av scripts/slurm_dca_array.sh hpc:/home/ad2347/OxPhos_DAV/scripts/
#
# ── SUBMIT ───────────────────────────────────────────────────────────────────
#   mkdir -p /work/WorkDevelopmentC/ad2347/OxPhos_DAV/logs /work/WorkDevelopmentC/ad2347/OxPhos_DAV/results/mutagenesis/dca_gene_results
#   sbatch /home/ad2347/OxPhos_DAV/scripts/slurm_dca_array.sh
#
# ── COPY RESULTS BACK ────────────────────────────────────────────────────────
#   rsync -av hpc:/work/WorkDevelopmentC/ad2347/OxPhos_DAV/results/mutagenesis/dca_gene_results/ \
#       results/mutagenesis/dca_gene_results/
#
# ── AGGREGATE LOCALLY ────────────────────────────────────────────────────────
#   docker run --rm -v $(pwd):/app oxphos_dav_analysis conda run -n oxphos_dav \
#       python src/mutagenesis/03_dca_all_davs.py \
#       --aggregate results/mutagenesis/dca_gene_results/
# ─────────────────────────────────────────────────────────────────────────────

set -euo pipefail

HPC_HOME="/home/ad2347/OxPhos_DAV"
HPC_WORK="/work/WorkDevelopmentC/ad2347/OxPhos_DAV"
GENES=(ATP5F1A ATP5F1B ATP5F1C ATP5F1D ATP5F1E ATP5IF1 ATP5MC1 ATP5MC2 ATP5MC3 ATP5ME ATP5MF ATP5MG ATP5MJ ATP5PO COX4I1 COX4I2 COX5A COX5B COX6A1 COX6A2 COX6B1 COX6C COX7A1 COX7A2 COX7B COX7C COX8A COXFA4 CYC1 MT-ATP6 MT-ATP8 MT-ND1 MT-ND2 MT-ND3 MT-ND4 MT-ND4L MT-ND5 MT-ND6 NDUFA1 NDUFA10 NDUFA11 NDUFA12 NDUFA13 NDUFA2 NDUFA3 NDUFA5 NDUFA6 NDUFA7 NDUFA8 NDUFA9 NDUFAB1 NDUFB1 NDUFB10 NDUFB11 NDUFB2 NDUFB3 NDUFB4 NDUFB5 NDUFB6 NDUFB7 NDUFB8 NDUFB9 NDUFC1 NDUFC2 NDUFS1 NDUFS2 NDUFS3 NDUFS4 NDUFS5 NDUFS6 NDUFS7 NDUFS8 NDUFV1 NDUFV2 NDUFV3 SDHA SDHB SDHC SDHD UQCR10 UQCR11 UQCRB UQCRC1 UQCRC2 UQCRFS1 UQCRH UQCRQ)
GENE="${GENES[${SLURM_ARRAY_TASK_ID}-1]}"

module load miniconda/2024-02-20
eval "$(conda shell.bash hook)"
conda activate OXPHOS_DAV

export OMP_NUM_THREADS=${SLURM_CPUS_PER_TASK:-8}
export OPENBLAS_NUM_THREADS=${SLURM_CPUS_PER_TASK:-8}
export MKL_NUM_THREADS=${SLURM_CPUS_PER_TASK:-8}

mkdir -p "$HPC_WORK/logs" "$HPC_WORK/results/mutagenesis/dca_gene_results"

echo "Gene: $GENE  Host: $(hostname)  Date: $(date)"
echo "CPUs: ${SLURM_CPUS_PER_TASK:-8}  Mem: $(free -h | awk '/^Mem/{print $2}')"

python "$HPC_HOME/src/mutagenesis/03b_dca_gene_worker.py" \
    "$GENE" \
    "$HPC_WORK/data/dca_jobs/$GENE/aln.fasta" \
    "$HPC_WORK/results/mutagenesis/dca_gene_results/${GENE}.npz"

echo "Done: $GENE  $(date)"
