#!/bin/bash
#SBATCH --job-name=pagel_oxphos
#SBATCH --array=1-43
#SBATCH --cpus-per-task=1
#SBATCH --mem=4G
#SBATCH --time=6:00:00
#SBATCH --output=/work/WorkDevelopmentC/ad2347/OxPhos_DAV/logs/pagel_%A_%a.out
#SBATCH --error=/work/WorkDevelopmentC/ad2347/OxPhos_DAV/logs/pagel_%A_%a.err

# Auto-generated by src/phylo/prepare_pagel_hpc.py — do not edit manually.
#
# Transfer inputs (run locally first):
#   rsync -av data/phylo/pagel_jobs/ hpc:/work/WorkDevelopmentC/ad2347/OxPhos_DAV/data/phylo/pagel_jobs/
#   rsync -av src/ hpc:/home/ad2347/OxPhos_DAV/src/
#   rsync -av scripts/slurm_pagel_array.sh hpc:/home/ad2347/OxPhos_DAV/scripts/
#
# Submit on HPC:
#   mkdir -p /work/WorkDevelopmentC/ad2347/OxPhos_DAV/results/phylo/pagel_results /work/WorkDevelopmentC/ad2347/OxPhos_DAV/logs
#   sbatch /home/ad2347/OxPhos_DAV/scripts/slurm_pagel_array.sh
#
# Copy results back:
#   rsync -av hpc:/work/WorkDevelopmentC/ad2347/OxPhos_DAV/results/phylo/pagel_results/ data/phylo/pagel_results/
#
# Merge locally:
#   docker run --rm -v $(pwd):/app oxphos_dav_analysis conda run -n oxphos_dav \
#       python src/phylo/merge_pagel_results.py

set -euo pipefail

module load miniconda/2024-02-20
eval "$(conda shell.bash hook)"
conda activate OXPHOS_DAV

CHUNK=$(printf "%04d" ${SLURM_ARRAY_TASK_ID})
HPC_HOME="/home/ad2347/OxPhos_DAV"
HPC_WORK="/work/WorkDevelopmentC/ad2347/OxPhos_DAV"
PAGEL_JOBS="$HPC_WORK/data/phylo/pagel_jobs"
OUT_DIR="$HPC_WORK/results/phylo/pagel_results"
mkdir -p "$OUT_DIR" "$HPC_WORK/logs"

# Paths inside chunk TSV are relative to pagel_jobs/ — cd there first
cd "$PAGEL_JOBS"

Rscript "$HPC_HOME/src/phylo/pagel_discrete.R" \
    "chunks/chunk_${CHUNK}.tsv" \
    "$OUT_DIR/results_${CHUNK}.tsv"

echo "Done: chunk $CHUNK"
