#!/bin/bash
#SBATCH --job-name=pyvolve_perm
#SBATCH --array=0-49
#SBATCH --cpus-per-task=4
#SBATCH --mem=16G
#SBATCH --time=12:00:00
#SBATCH --output=/work/WorkDevelopmentC/ad2347/OxPhos_DAV/logs/pyvolve_%A_%a.out
#SBATCH --error=/work/WorkDevelopmentC/ad2347/OxPhos_DAV/logs/pyvolve_%A_%a.err
#SBATCH --export=ALL
#SBATCH --mail-type=FAIL,BEGIN,END
#SBATCH --mail-user=abhilesh7@gmail.com
#
# SLURM array for tree-aware conditional permutation (04_conditional_permissiveness.py).
# 50 tasks × ~27 unique contact positions each; 1,000 pyvolve simulations per position.
# Writes: results/phylo/conditional_permissiveness_chunk{NNNN}.csv
#
# ── SETUP (run locally first) ────────────────────────────────────────────────
#   rsync -av results/structural/all_tested_pairs.csv \
#       lambda:/work/WorkDevelopmentC/ad2347/OxPhos_DAV/results/structural/
#   rsync -av results/phylo/timing_annotations.csv \
#       lambda:/work/WorkDevelopmentC/ad2347/OxPhos_DAV/results/phylo/
#   rsync -av data/phylo/ancestral_state_maps.json \
#       lambda:/work/WorkDevelopmentC/ad2347/OxPhos_DAV/data/phylo/
#   rsync -av data/phylo/iqtree_jobs/ \
#       lambda:/work/WorkDevelopmentC/ad2347/OxPhos_DAV/data/phylo/iqtree_jobs/
#   # ancestral_states/ holds the .iqtree files used for per-gene model lookup;
#   # these are normally already on HPC (generated by slurm_iqtree_array.sh),
#   # but rsync here if running for the first time or after a local-only IQTree run:
#   rsync -av data/phylo/ancestral_states/ \
#       lambda:/work/WorkDevelopmentC/ad2347/OxPhos_DAV/data/phylo/ancestral_states/
#   rsync -av data/alignments/ \
#       lambda:/work/WorkDevelopmentC/ad2347/OxPhos_DAV/data/alignments/
#   rsync -av src/    lambda:/home/ad2347/OxPhos_DAV/src/
#   rsync -av setup.py lambda:/home/ad2347/OxPhos_DAV/
#   rsync -av scripts/slurm_pyvolve_perm.sh lambda:/home/ad2347/OxPhos_DAV/scripts/
#
# ── SUBMIT ───────────────────────────────────────────────────────────────────
#   mkdir -p /work/WorkDevelopmentC/ad2347/OxPhos_DAV/logs
#   mkdir -p /work/WorkDevelopmentC/ad2347/OxPhos_DAV/results/phylo
#   sbatch /home/ad2347/OxPhos_DAV/scripts/slurm_pyvolve_perm.sh
#
# ── COPY CHUNKS BACK ─────────────────────────────────────────────────────────
#   rsync -av \
#       hpc:/work/WorkDevelopmentC/ad2347/OxPhos_DAV/results/phylo/conditional_permissiveness_chunk*.csv \
#       results/phylo/
#
# ── MERGE LOCALLY ────────────────────────────────────────────────────────────
#   docker run --rm -v $(pwd):/app oxphos_dav_analysis conda run -n oxphos_dav \
#       python src/phylo/05_merge_perm_chunks.py
# ─────────────────────────────────────────────────────────────────────────────

set -euo pipefail

HPC_HOME="/home/ad2347/OxPhos_DAV"
HPC_WORK="/work/WorkDevelopmentC/ad2347/OxPhos_DAV"
N_CHUNKS=50
N_PERM=1000

module load miniconda/2024-02-20
eval "$(conda shell.bash hook)"
conda activate OXPHOS_DAV

export OMP_NUM_THREADS=${SLURM_CPUS_PER_TASK:-4}

mkdir -p "${HPC_WORK}/logs" "${HPC_WORK}/results/phylo"

echo "Starting chunk ${SLURM_ARRAY_TASK_ID} of ${N_CHUNKS} (n_perm=${N_PERM})"
echo "Host: $(hostname)  Date: $(date)"

python "${HPC_HOME}/src/phylo/04_conditional_permissiveness.py" \
    --chunk-idx "${SLURM_ARRAY_TASK_ID}" \
    --n-chunks  "${N_CHUNKS}" \
    --n-perm    "${N_PERM}" \
    --work-dir  "${HPC_WORK}"

echo "Finished chunk ${SLURM_ARRAY_TASK_ID}  $(date)"
